2025-07-10 11:38:40,720 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-07-10 11:38:40,722 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-07-10 11:38:40,722 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco Saude']
2025-07-10 11:38:40,723 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-07-10 11:38:40,725 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bdc_saude WHERE competencia = '01-2025' LIMIT 1;
2025-07-10 11:38:40,733 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco Saude na competência 01-2025
2025-07-10 11:38:40,734 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Encerrando execução.
2025-07-10 11:38:40,736 - extrato_app.CoreData.batch_runner - INFO - Log de execuções puladas salvo em: conta_virtual_012025.txt
2025-07-10 11:38:40,736 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-07-10 11:38:40,739 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-07-10 11:38:40,743 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bdc_saude WHERE competencia = '01-2025' LIMIT 1;
2025-07-10 11:38:40,746 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco Saude na competência 01-2025
2025-07-10 11:38:40,747 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-07-10 11:38:43,792 - django.request - WARNING - Not Found: /media/inconsistencias_conta_virtual_012025.txt
2025-07-10 11:40:04,600 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
