2025-08-14 10:49:39,779 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 10:49:59,482 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 10:50:05,434 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 10:52:02,047 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 10:52:04,215 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 10:52:09,662 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 10:52:09,662 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 10:52:09,663 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 10:52:09,663 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 10:52:09,664 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 10:52:09,675 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 10:52:09,677 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-14 10:52:09,677 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 10:52:09,678 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 10:52:09,679 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 10:52:09,682 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 10:52:09,683 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 10:52:22,169 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 10:52:28,216 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 10:52:28,216 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 10:52:28,216 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 10:52:28,217 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 10:52:28,219 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 10:52:28,227 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 10:52:28,227 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 10:52:32,689 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 10:52:32,689 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 10:52:32,692 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 10:52:32,696 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 10:52:32,700 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 10:52:32,702 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 10:52:32,793 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 4.58 segundos
2025-08-14 10:59:57,297 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-14 11:00:01,032 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-14 11:00:10,474 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:00:42,617 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-14 11:00:48,259 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:00:58,785 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:01:24,322 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:01:24,323 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:01:24,323 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:01:24,323 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:01:24,324 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:01:24,337 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:01:24,339 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-14 11:01:24,339 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:01:24,340 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:01:24,341 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:01:24,343 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:01:24,345 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:01:36,074 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:01:36,074 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:01:36,075 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:01:36,075 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:01:36,076 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:01:36,084 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:01:36,084 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:01:41,556 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 11:01:41,556 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:01:41,560 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:01:41,563 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:01:41,567 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:01:41,569 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:01:41,688 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.61 segundos
2025-08-14 11:07:01,072 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:07:09,290 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:07:48,785 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:08:25,773 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:08:34,618 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:08:37,601 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:08:58,856 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:09:03,137 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:09:03,138 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:09:03,138 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:09:03,138 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:09:03,139 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:09:03,150 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:09:03,150 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:09:07,896 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com falha
2025-08-14 11:09:07,897 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:09:07,900 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:09:07,904 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:09:07,911 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:09:08,114 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 4.98 segundos
2025-08-14 11:11:06,275 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:11:08,367 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:11:08,367 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:11:08,367 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:11:08,367 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:11:08,368 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:11:08,380 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:11:08,380 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:11:12,466 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 11:11:12,467 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:11:12,468 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:11:12,473 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:11:12,475 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:11:12,477 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:11:12,693 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 4.33 segundos
2025-08-14 11:16:43,813 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:20:11,474 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:20:21,936 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:20:26,926 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:20:26,926 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:20:26,926 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:20:26,926 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:20:26,927 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:20:26,939 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:20:26,939 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:20:32,710 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 11:20:32,710 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:20:32,712 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:20:32,713 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:20:32,716 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:20:32,718 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:20:32,909 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.98 segundos
2025-08-14 11:41:35,499 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:45:33,937 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:45:52,458 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:46:19,550 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:46:25,317 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:46:36,097 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:46:36,098 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:46:36,099 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:46:36,099 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:46:36,102 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:46:36,117 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:46:36,117 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:46:41,533 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 11:46:41,535 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:46:41,536 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:46:41,537 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:46:41,540 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:46:41,541 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:46:41,715 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.62 segundos
2025-08-14 11:55:09,133 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:55:14,623 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:55:28,560 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:55:33,243 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:55:33,244 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:55:33,244 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:55:33,244 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:55:33,246 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:55:33,256 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:55:33,260 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-14 11:55:33,260 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:55:33,262 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:55:33,264 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:55:33,268 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:55:33,271 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:55:43,527 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:55:43,527 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:55:43,527 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:55:43,527 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:55:43,528 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:55:43,536 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:55:43,536 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 11:55:48,935 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 11:55:48,935 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:55:48,939 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:55:48,942 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:55:48,946 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:55:48,949 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:55:49,038 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.51 segundos
2025-08-14 11:59:14,970 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:59:28,865 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 11:59:43,567 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 11:59:48,237 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:59:48,237 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:59:48,238 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:59:48,238 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:59:48,239 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:59:48,242 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:59:48,243 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-14 11:59:48,244 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 11:59:48,246 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:59:48,248 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:59:48,249 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 11:59:48,251 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 11:59:56,640 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 11:59:56,640 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 11:59:56,641 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 11:59:56,641 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 11:59:56,642 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 11:59:56,649 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 11:59:56,650 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 12:00:01,693 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 12:00:01,693 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 12:00:01,696 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 12:00:01,699 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 12:00:01,704 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 12:00:01,705 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 12:00:01,786 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.15 segundos
2025-08-14 12:02:52,989 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 12:03:01,523 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 12:03:13,115 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 12:03:18,692 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 12:03:18,692 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 12:03:18,692 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 12:03:18,693 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 12:03:18,694 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 12:03:18,712 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 12:03:18,712 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 12:03:24,262 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 12:03:24,262 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 12:03:24,263 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 12:03:24,264 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 12:03:24,268 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 12:03:24,270 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 12:03:24,450 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.76 segundos
2025-08-14 13:25:08,462 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AxaHandler.py changed, reloading.
2025-08-14 13:36:38,558 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-14 13:36:59,977 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:37:18,091 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-14 13:39:51,610 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:39:58,000 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:40:02,261 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-14 13:41:08,912 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 13:41:15,421 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 13:41:15,421 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 13:41:15,421 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 13:41:15,422 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:41:15,423 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:41:15,435 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 13:41:15,436 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 13:41:20,450 - extrato_app.CoreData.batch_runner - ERROR - Erro ao processar Allianz-01-2025: arg must be a list, tuple, 1-d array, or Series
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\batch_runner.py", line 199, in executar_combinações
    success, processed_data = importer.execute_pipeline()
                              ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\CoreMain.py", line 177, in execute_pipeline
    processed_data = self.data_handler.treat_zero(file_dfs, id_cia)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py", line 305, in treat_zero
    df_filtered = self.convert_df_to_db_schema(df_filtered, column_types)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py", line 111, in convert_df_to_db_schema
    df[col] = pd.to_numeric(df[col], errors='coerce')
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\tools\numeric.py", line 206, in to_numeric
    raise TypeError("arg must be a list, tuple, 1-d array, or Series")
TypeError: arg must be a list, tuple, 1-d array, or Series

2025-08-14 13:41:20,452 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 13:41:20,456 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:41:20,460 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:41:20,465 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 13:41:20,659 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.24 segundos
2025-08-14 13:42:40,806 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-14 13:43:10,084 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 13:43:23,554 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 13:43:23,555 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 13:43:23,555 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 13:43:23,555 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:43:23,557 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:43:23,570 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 13:43:23,570 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 13:43:28,634 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 13:43:28,634 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 13:43:28,636 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:43:28,639 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:43:28,644 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 13:43:28,646 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 13:43:28,801 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.25 segundos
2025-08-14 13:43:41,524 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 13:46:33,054 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:46:51,896 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:46:56,753 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:47:27,070 - django.request - WARNING - Not Found: /favicon.ico
2025-08-14 13:47:30,127 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-14 13:47:36,779 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 13:47:36,780 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 13:47:36,780 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-14 13:47:36,780 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:47:36,783 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:47:36,802 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-14 13:47:36,803 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-14 13:47:42,062 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-14 13:47:42,063 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 13:47:42,065 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:47:42,068 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:47:42,073 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-14 13:47:42,075 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 13:47:42,234 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.45 segundos
2025-08-14 13:49:30,667 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-14 13:49:30,667 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-14 13:49:30,668 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-14 13:49:30,671 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:49:30,674 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:49:30,683 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco']
2025-08-14 13:49:30,683 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-14 13:49:46,266 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com sucesso
2025-08-14 13:49:46,266 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-14 13:49:46,271 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-14 13:49:46,276 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-14 13:49:46,280 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-14 13:49:46,282 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-14 13:49:46,384 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 15.72 segundos
2025-08-14 14:20:25,835 - django.request - ERROR - Internal Server Error: /api/buscar-cias/
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 191, in buscar_cias_api
    existing, non_existing, lista_cias, id_cia = dba.get_and_compare_cias()
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py", line 401, in get_and_compare_cias
    cursor.execute("SELECT distinct seg_nome_correto from tabela_correcao_seguradora")
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2025-08-15 09:33:52,773 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:33:52,775 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:33:52,776 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-15 09:33:52,778 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:33:52,781 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:33:52,786 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-15 09:33:52,786 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-15 09:33:58,750 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-15 09:33:58,751 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:33:58,752 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:33:58,754 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:33:58,756 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-15 09:33:58,758 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:33:58,995 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 6.22 segundos
2025-08-15 09:34:45,448 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AllianzHandler.py changed, reloading.
2025-08-15 09:34:55,431 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 09:35:28,777 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 09:35:59,029 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:35:59,030 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:35:59,030 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-15 09:35:59,030 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:35:59,031 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:35:59,035 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Allianz']
2025-08-15 09:35:59,036 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Allianz - 01-2025
2025-08-15 09:36:04,324 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Allianz com sucesso
2025-08-15 09:36:04,324 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:36:04,325 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:36:04,327 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:36:04,329 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-15 09:36:04,330 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:36:04,467 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 5.44 segundos
2025-08-15 09:38:58,704 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 09:39:11,650 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:39:22,482 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:39:29,864 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:39:29,864 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:39:29,864 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-15 09:39:29,864 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:39:29,865 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:39:29,869 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco']
2025-08-15 09:39:29,869 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-15 09:39:32,506 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:39:32,512 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:39:32,520 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-15 09:39:32,525 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:39:32,577 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:39:32,606 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco']
2025-08-15 09:39:32,613 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-15 09:39:48,797 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com falha
2025-08-15 09:39:48,804 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:39:48,882 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:39:48,928 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:39:48,951 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:39:50,237 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 20.37 segundos
2025-08-15 09:39:51,038 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com falha
2025-08-15 09:39:51,039 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:39:51,042 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:39:51,047 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:39:51,051 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:39:51,102 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 18.59 segundos
2025-08-15 09:40:09,565 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:40:21,690 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:40:21,690 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:40:21,691 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Allianz']
2025-08-15 09:40:21,691 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:40:21,692 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:40:21,695 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-15 09:40:21,696 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-15 09:40:21,696 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:40:21,697 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:40:21,698 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_allianz WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:40:21,700 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Allianz na competência 01-2025
2025-08-15 09:40:21,701 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:40:39,693 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 09:40:53,437 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:40:53,438 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:40:53,438 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-15 09:40:53,438 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:40:53,439 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:40:53,442 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco']
2025-08-15 09:40:53,442 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-15 09:41:04,286 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com falha
2025-08-15 09:41:04,287 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:41:04,288 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:41:04,291 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:41:04,293 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:41:04,442 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 11.00 segundos
2025-08-15 09:46:36,915 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:46:49,811 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:47:03,703 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 09:48:03,076 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:48:03,076 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:48:03,076 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-15 09:48:03,076 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:48:03,077 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:48:03,083 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco']
2025-08-15 09:48:03,084 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-15 09:48:17,123 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com sucesso
2025-08-15 09:48:17,123 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:48:17,127 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:48:17,131 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:48:17,134 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-15 09:48:17,136 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:48:17,251 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 14.18 segundos
2025-08-15 09:54:45,421 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 09:57:17,017 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoSaudeHandler.py changed, reloading.
2025-08-15 09:57:20,510 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoSaudeHandler.py changed, reloading.
2025-08-15 09:57:23,265 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoSaudeHandler.py changed, reloading.
2025-08-15 09:59:13,052 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 09:59:13,053 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-15 09:59:13,053 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco Saude']
2025-08-15 09:59:13,053 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:59:13,054 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bdc_saude WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:59:13,062 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco Saude']
2025-08-15 09:59:13,063 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco Saude - 01-2025
2025-08-15 09:59:14,240 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco Saude com sucesso
2025-08-15 09:59:14,240 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 09:59:14,241 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 09:59:14,242 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bdc_saude WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 09:59:14,244 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco Saude na competência 01-2025
2025-08-15 09:59:14,246 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-15 09:59:14,368 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 1.32 segundos
2025-08-15 10:02:08,067 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AxaHandler.py changed, reloading.
2025-08-15 10:09:04,803 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 10:24:20,053 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\AxaHandler.py changed, reloading.
2025-08-15 10:25:03,403 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\ChubbHandler.py changed, reloading.
2025-08-15 10:25:21,459 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\EzzeHandler.py changed, reloading.
2025-08-15 10:25:25,399 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\BradescoHandler.py changed, reloading.
2025-08-15 10:25:36,630 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\HDIHandler.py changed, reloading.
2025-08-15 10:25:42,636 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\JuntoHandler.py changed, reloading.
2025-08-15 10:25:58,621 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\PortoHandler.py changed, reloading.
2025-08-15 10:26:07,977 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\PortoHandler.py changed, reloading.
2025-08-15 10:26:16,598 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\SompoHandler.py changed, reloading.
2025-08-15 10:26:37,818 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\SompoHandler.py changed, reloading.
2025-08-15 10:26:42,702 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\SuhaiHandler.py changed, reloading.
2025-08-15 10:26:45,427 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\SuhaiHandler.py changed, reloading.
2025-08-15 10:26:56,442 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\SwissHandler.py changed, reloading.
2025-08-15 10:27:05,142 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\TokioHandler.py changed, reloading.
2025-08-15 10:27:07,791 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\YelumHandler.py changed, reloading.
2025-08-15 10:27:11,203 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\YelumHandler.py changed, reloading.
2025-08-15 10:27:15,087 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\ZurichHandler.py changed, reloading.
2025-08-15 10:27:17,680 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\Handlers\ZurichHandler.py changed, reloading.
2025-08-15 10:34:18,201 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 10:35:10,272 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 10:35:10,272 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 13 CIAs e competência 01-2025
2025-08-15 10:35:10,273 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Suhai', 'Junto Seguradora', 'Hdi', 'Porto', 'Yelum', 'Axa', 'Zurich', 'Tokio', 'Chubb', 'Ezze', 'Sompo', 'Swiss', 'Mapfre']
2025-08-15 10:35:10,273 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 10:35:10,274 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_suhai WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,277 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_junto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,279 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,282 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_porto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,284 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_yelum WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,285 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_axa WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,287 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_zurich WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,289 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_tokio WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,290 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_chubb WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,292 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_ezze WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,293 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_sompo WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,294 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_swiss WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,295 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_mapfre WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:35:10,298 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Suhai', 'Junto Seguradora', 'Hdi', 'Porto', 'Yelum', 'Axa', 'Zurich', 'Tokio', 'Chubb', 'Ezze', 'Sompo', 'Swiss', 'Mapfre']
2025-08-15 10:35:10,298 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Suhai - 01-2025
2025-08-15 10:35:11,564 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Suhai com sucesso
2025-08-15 10:35:11,564 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Junto Seguradora - 01-2025
2025-08-15 10:36:18,246 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Junto Seguradora com sucesso
2025-08-15 10:36:18,246 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Hdi - 01-2025
2025-08-15 10:36:57,675 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Hdi com sucesso
2025-08-15 10:36:57,675 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Porto - 01-2025
2025-08-15 10:37:00,171 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Porto com sucesso
2025-08-15 10:37:00,172 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Yelum - 01-2025
2025-08-15 10:37:00,908 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Yelum com sucesso
2025-08-15 10:37:00,908 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Axa - 01-2025
2025-08-15 10:37:02,814 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Axa com falha
2025-08-15 10:37:02,815 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Zurich - 01-2025
2025-08-15 10:37:06,537 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Zurich com sucesso
2025-08-15 10:37:06,537 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Tokio - 01-2025
2025-08-15 10:37:12,375 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Tokio com sucesso
2025-08-15 10:37:12,375 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Chubb - 01-2025
2025-08-15 10:37:13,611 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Chubb com sucesso
2025-08-15 10:37:13,611 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Ezze - 01-2025
2025-08-15 10:37:14,893 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Ezze com falha
2025-08-15 10:37:14,893 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Sompo - 01-2025
2025-08-15 10:37:16,652 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Sompo com sucesso
2025-08-15 10:37:16,653 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Swiss - 01-2025
2025-08-15 10:37:19,293 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Swiss com sucesso
2025-08-15 10:37:19,294 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Mapfre - 01-2025
2025-08-15 10:37:19,998 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Mapfre com sucesso
2025-08-15 10:37:19,999 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 10:37:20,002 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 10:37:20,006 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_suhai WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,009 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Suhai na competência 01-2025
2025-08-15 10:37:20,010 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_junto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,012 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Junto Seguradora na competência 01-2025
2025-08-15 10:37:20,013 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,023 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-15 10:37:20,024 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_porto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,026 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Porto na competência 01-2025
2025-08-15 10:37:20,027 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_yelum WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,029 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Yelum na competência 01-2025
2025-08-15 10:37:20,030 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_axa WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,031 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_zurich WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,033 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Zurich na competência 01-2025
2025-08-15 10:37:20,034 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_tokio WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,035 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Tokio na competência 01-2025
2025-08-15 10:37:20,036 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_chubb WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,037 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Chubb na competência 01-2025
2025-08-15 10:37:20,038 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_ezze WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,039 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_sompo WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,041 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Sompo na competência 01-2025
2025-08-15 10:37:20,041 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_swiss WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,043 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Swiss na competência 01-2025
2025-08-15 10:37:20,044 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_mapfre WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:37:20,046 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Mapfre na competência 01-2025
2025-08-15 10:37:20,049 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 13 CIAs (solicitadas + geradas anteriormente)
2025-08-15 10:37:20,393 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 130.12 segundos
2025-08-15 10:51:09,835 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 16 CIAs disponíveis
2025-08-15 10:51:09,836 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 13 CIAs e competência 01-2025
2025-08-15 10:51:09,836 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Suhai', 'Junto Seguradora', 'Hdi', 'Porto', 'Yelum', 'Axa', 'Zurich', 'Tokio', 'Chubb', 'Ezze', 'Sompo', 'Swiss', 'Mapfre']
2025-08-15 10:51:09,836 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 10:51:09,838 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_suhai WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,843 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Suhai na competência 01-2025
2025-08-15 10:51:09,844 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_junto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,845 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Junto Seguradora na competência 01-2025
2025-08-15 10:51:09,846 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,849 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-15 10:51:09,849 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_porto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,853 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Porto na competência 01-2025
2025-08-15 10:51:09,853 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_yelum WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,856 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Yelum na competência 01-2025
2025-08-15 10:51:09,856 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_axa WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,858 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_zurich WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,860 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Zurich na competência 01-2025
2025-08-15 10:51:09,860 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_tokio WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,863 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Tokio na competência 01-2025
2025-08-15 10:51:09,863 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_chubb WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,865 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Chubb na competência 01-2025
2025-08-15 10:51:09,865 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_ezze WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,867 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_sompo WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,868 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Sompo na competência 01-2025
2025-08-15 10:51:09,869 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_swiss WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,870 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Swiss na competência 01-2025
2025-08-15 10:51:09,870 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_mapfre WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:09,872 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Mapfre na competência 01-2025
2025-08-15 10:51:09,874 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Axa', 'Ezze']
2025-08-15 10:51:09,875 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Axa - 01-2025
2025-08-15 10:51:11,494 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Axa com falha
2025-08-15 10:51:11,494 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Ezze - 01-2025
2025-08-15 10:51:12,828 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Ezze com falha
2025-08-15 10:51:12,828 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-15 10:51:12,830 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-15 10:51:12,834 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_axa WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,837 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_ezze WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,838 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_suhai WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,840 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Suhai na competência 01-2025
2025-08-15 10:51:12,841 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_junto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,843 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Junto Seguradora na competência 01-2025
2025-08-15 10:51:12,844 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,845 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-15 10:51:12,845 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_porto WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,847 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Porto na competência 01-2025
2025-08-15 10:51:12,847 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_yelum WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,848 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Yelum na competência 01-2025
2025-08-15 10:51:12,849 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_zurich WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,850 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Zurich na competência 01-2025
2025-08-15 10:51:12,851 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_tokio WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,852 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Tokio na competência 01-2025
2025-08-15 10:51:12,852 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_chubb WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,854 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Chubb na competência 01-2025
2025-08-15 10:51:12,854 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_sompo WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,855 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Sompo na competência 01-2025
2025-08-15 10:51:12,856 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_swiss WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,859 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Swiss na competência 01-2025
2025-08-15 10:51:12,859 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_mapfre WHERE competencia = '01-2025' LIMIT 1;
2025-08-15 10:51:12,860 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Mapfre na competência 01-2025
2025-08-15 10:51:12,862 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 13 CIAs (solicitadas + geradas anteriormente)
2025-08-15 10:51:13,230 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 3.39 segundos
2025-08-15 11:53:20,946 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 11:55:37,214 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:02:22,058 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:02:29,137 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:02:37,111 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:02:41,235 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:03:03,323 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:03:12,207 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:04:13,716 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:04:18,463 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 12:04:21,026 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 13:32:30,751 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\trat_rec.py changed, reloading.
2025-08-15 13:46:26,297 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 13:47:02,415 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 13:47:21,796 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 13:47:31,810 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 13:47:37,815 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 14:14:01,543 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-15 14:15:35,509 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-15 14:15:42,866 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-15 14:16:15,727 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-15 14:16:18,409 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 14:17:19,764 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-15 14:24:40,881 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 14:24:53,534 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 14:24:58,978 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 14:55:57,568 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\data_handler.py changed, reloading.
2025-08-15 14:56:02,221 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-15 15:44:16,940 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 15:48:55,998 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 15:52:28,287 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 15:52:52,526 - django.request - WARNING - Not Found: /favicon.ico
2025-08-15 15:57:38,885 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-15 17:10:58,500 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 10:59:18,459 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:04:26,292 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:05:21,300 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:27:35,793 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:27:39,066 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:30:30,541 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 11:44:25,148 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 11:44:31,453 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 13:51:43,232 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 14:53:05,255 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 14:59:09,578 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 14:59:17,196 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 14:59:20,220 - django.request - WARNING - Method Not Allowed: /executar-atualizar-caixa
2025-08-18 14:59:29,719 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 14:59:29,858 - django.request - WARNING - Method Not Allowed: /executar-atualizar-caixa
2025-08-18 15:03:45,103 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 15:06:28,568 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 15:32:49,177 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-18 15:35:40,314 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 147, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-18 15:40:42,423 - django.request - WARNING - Not Found: /favicon.ico
2025-08-18 15:42:00,882 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-18 15:43:59,653 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-18 15:50:15,246 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:35:00,238 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:35:05,616 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:44:21,524 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:44:22,526 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:44:23,417 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:44:23,668 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:44:23,858 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:44:37,216 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:52:40,333 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:52:40,835 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:52:41,005 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:53:03,066 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:53:03,242 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:53:10,405 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:53:12,190 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:59:09,041 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 09:59:20,300 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 09:59:44,533 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:59:44,890 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:59:54,837 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:59:56,368 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 09:59:56,541 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 09:59:56,743 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:04:36,089 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:04:38,626 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:04:41,041 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:04:43,077 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:04:43,792 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:06:45,238 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 10:07:07,864 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:07:08,948 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:07:09,113 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 10:33:55,296 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:34:35,448 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:40:20,205 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:40:24,507 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:40:24,660 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 10:40:24,800 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:40:42,821 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:40:45,318 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:45:39,089 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:45:40,513 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:45:41,364 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:52:31,038 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:52:31,831 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:52:32,484 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:52:33,336 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 10:58:58,578 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 10:59:12,624 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 10:59:16,616 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 11:00:00,671 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:00:05,538 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:00:05,796 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 11:00:06,317 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:02:26,517 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:13:24,917 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:14:26,386 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:17:35,955 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:18:27,661 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:18:33,778 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:18:38,410 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:18:41,323 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:19:08,568 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:19:14,589 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:19:19,446 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:19:19,821 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:19:20,038 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 11:19:38,689 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 11:43:13,224 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:43:15,879 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:43:17,696 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:50:09,698 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-19 11:51:32,768 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 11:51:50,544 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 13:31:43,920 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 13:41:28,053 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:41:33,996 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:41:55,934 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 13:42:18,885 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-19 13:44:27,199 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 13:44:33,114 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 13:48:29,258 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 13:49:22,194 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-19 13:50:13,819 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:51:17,325 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:51:22,822 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:51:31,473 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:51:43,051 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:52:05,675 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:54:26,107 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:54:32,531 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:54:36,647 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:55:13,330 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 13:55:38,780 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 13:57:52,439 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 14:04:06,927 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 14:04:11,078 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 14:17:44,642 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 14:18:46,835 - django.request - WARNING - Not Found: /favicon.ico
2025-08-19 15:27:16,231 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 15:35:19,353 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 15:35:28,150 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 15:37:17,830 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 15:47:59,077 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 15:55:28,714 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 16:06:25,132 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-19 16:25:04,519 - django.request - WARNING - Not Found: /favicon.ico
